# Generated by Django 4.2.30 on 2026-09-13 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reputation', to='profiles.socialprofile')),
            ],
            options={
                'db_table': 'social_reputations',
            },
        ),
        migrations.CreateModel(
            name='SocialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('harassment', 'Harassment'), ('hate', 'Hate'), ('spam', 'Spam'), ('impersonation', 'Impersonation'), ('inappropriate', 'Inappropriate'), ('other', 'Other')], max_length=32)),
                ('details', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to='profiles.socialprofile')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_created', to='profiles.socialprofile')),
            ],
            options={
                'db_table': 'social_reports',
            },
        ),
        migrations.CreateModel(
            name='SocialMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('muted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutes_received', to='profiles.socialprofile')),
                ('muter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutes_created', to='profiles.socialprofile')),
            ],
            options={
                'db_table': 'social_mutes',
            },
        ),
        migrations.CreateModel(
            name='SocialBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to='profiles.socialprofile')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_created', to='profiles.socialprofile')),
            ],
            options={
                'db_table': 'social_blocks',
            },
        ),
        migrations.AddConstraint(
            model_name='socialreputation',
            constraint=models.CheckConstraint(check=models.Q(('score__gte', 0), ('score__lte', 100)), name='social_reputation_0_100'),
        ),
        migrations.AddIndex(
            model_name='socialreport',
            index=models.Index(fields=['reported', 'created_at'], name='social_report_target_idx'),
        ),
        migrations.AddIndex(
            model_name='socialreport',
            index=models.Index(fields=['reporter', 'created_at'], name='social_report_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialreport',
            constraint=models.CheckConstraint(check=models.Q(('reporter', models.F('reported')), _negated=True), name='social_report_not_self'),
        ),
        migrations.AddIndex(
            model_name='socialmute',
            index=models.Index(fields=['muter', 'muted'], name='social_mute_pair_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialmute',
            constraint=models.UniqueConstraint(fields=('muter', 'muted'), name='social_unique_mute'),
        ),
        migrations.AddConstraint(
            model_name='socialmute',
            constraint=models.CheckConstraint(check=models.Q(('muter', models.F('muted')), _negated=True), name='social_mute_not_self'),
        ),
        migrations.AddIndex(
            model_name='socialblock',
            index=models.Index(fields=['blocker', 'blocked'], name='social_block_pair_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialblock',
            constraint=models.UniqueConstraint(fields=('blocker', 'blocked'), name='social_unique_block'),
        ),
        migrations.AddConstraint(
            model_name='socialblock',
            constraint=models.CheckConstraint(check=models.Q(('blocker', models.F('blocked')), _negated=True), name='social_block_not_self'),
        ),
    ]
