# Generated by Django 4.2.30 on 2026-09-13 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_socialreputation_socialreport_socialmute_socialblock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('limited', 'Limited'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to='profiles.socialprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_social_moderations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_moderations',
                'indexes': [models.Index(fields=['status'], name='social_mod_status_idx')],
            },
        ),
    ]
