# Generated by Django 4.2.30 on 2026-09-13 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_socialmoderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests_sent', to='profiles.socialprofile')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests_received', to='profiles.socialprofile')),
            ],
            options={
                'db_table': 'social_connections',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['requester', 'status'], name='social_conn_requester_idx'), models.Index(fields=['target', 'status'], name='social_conn_target_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='socialconnection',
            constraint=models.UniqueConstraint(fields=('requester', 'target'), name='social_connection_unique_direction'),
        ),
        migrations.AddConstraint(
            model_name='socialconnection',
            constraint=models.CheckConstraint(check=models.Q(('requester', models.F('target')), _negated=True), name='social_connection_no_self'),
        ),
    ]
