# Generated by Django 4.2.30 on 2026-05-30 20:19

from django.conf import settings
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=100)),
                ('lastname', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('preferences', models.JSONField(default=dict)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('synopsis', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('movie', 'Film'), ('series', 'Série')], db_index=True, max_length=20)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('poster_url', models.URLField(blank=True, max_length=500)),
                ('backdrop_url', models.URLField(blank=True, max_length=500)),
                ('banner_url', models.URLField(blank=True, max_length=500)),
                ('video_url', models.URLField(blank=True, max_length=500)),
                ('trailer_url', models.URLField(blank=True, max_length=500)),
                ('release_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Durée en minutes', null=True)),
                ('age_rating', models.CharField(blank=True, max_length=10)),
                ('is_hd', models.BooleanField(default=True)),
                ('is_4k', models.BooleanField(default=False)),
                ('is_hdr', models.BooleanField(default=False)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_count', models.IntegerField(default=0)),
                ('view_count', models.BigIntegerField(default=0)),
                ('popularity_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ia_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('trending_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_until', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contents',
            },
        ),
        migrations.CreateModel(
            name='ContentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'content_status',
            },
        ),
        migrations.CreateModel(
            name='CustomList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'custom_lists',
            },
        ),
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField(db_index=True, unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_views', models.BigIntegerField(default=0)),
                ('total_watch_time', models.BigIntegerField(default=0, help_text='Secondes totales')),
                ('new_subscriptions', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_stats',
                'ordering': ['-stat_date'],
            },
        ),
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'emissions',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('template', models.TextField(blank=True)),
                ('is_push_enabled', models.BooleanField(default=True)),
                ('is_email_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notification_types',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('pin_code', models.CharField(blank=True, max_length=6)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_age_restriction', models.IntegerField(blank=True, null=True)),
                ('can_create_lists', models.BooleanField(default=True)),
                ('can_rate_content', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'profile_types',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('duration_days', models.IntegerField()),
                ('max_profiles', models.IntegerField(default=4)),
                ('max_devices', models.IntegerField(default=4)),
                ('max_quality', models.CharField(blank=True, choices=[('SD', 'SD'), ('HD', 'HD'), ('FULL_HD', 'Full HD'), ('4K', '4K')], max_length=20)),
                ('ads_included', models.BooleanField(default=False)),
                ('download_enabled', models.BooleanField(default=True)),
                ('features', models.JSONField(default=list)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'subscription_plans',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('device_type', models.CharField(max_length=50)),
                ('refresh_token', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('cancelled', 'Annulé'), ('pending', 'En attente')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season_number', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('episode_count', models.IntegerField(default=0)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='core.content')),
            ],
            options={
                'db_table': 'seasons',
                'ordering': ['season_number'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reason', models.CharField(blank=True, choices=[('similar_genre', 'Genres similaires'), ('trending', 'Tendance'), ('because_you_watched', 'Parce que vous avez regardé'), ('popular', 'Populaire'), ('ai_match', 'Correspondance IA')], max_length=50)),
                ('is_viewed', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.content')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.profile')),
            ],
            options={
                'db_table': 'recommendations',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('review', models.TextField(blank=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.content')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.profile')),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profiletype'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('provider', models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('orange_money', 'Orange Money'), ('mtn_money', 'MTN Money'), ('wave', 'Wave')], max_length=50)),
                ('provider_payment_id', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.subscription')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('data', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.notificationtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_order', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.content')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.customlist')),
            ],
            options={
                'db_table': 'list_items',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'genres',
                'indexes': [models.Index(fields=['name'], name='genres_name_4778a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.content')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='core.profile')),
            ],
            options={
                'db_table': 'favorites',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration', models.IntegerField(blank=True, help_text='Durée en minutes', null=True)),
                ('video_url', models.URLField(blank=True, max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.content')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.season')),
            ],
            options={
                'db_table': 'episodes',
                'ordering': ['episode_number'],
            },
        ),
        migrations.AddField(
            model_name='customlist',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_lists', to='core.profile'),
        ),
        migrations.CreateModel(
            name='ContentSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('content_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='core.content')),
                ('content_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_from', to='core.content')),
            ],
            options={
                'db_table': 'content_similarity',
            },
        ),
        migrations.CreateModel(
            name='ContentGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.content')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.genre')),
            ],
            options={
                'db_table': 'content_genres',
            },
        ),
        migrations.CreateModel(
            name='ContentEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.content')),
                ('emission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.emission')),
            ],
            options={
                'db_table': 'content_emissions',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='emissions',
            field=models.ManyToManyField(related_name='contents', through='core.ContentEmission', to='core.emission'),
        ),
        migrations.AddField(
            model_name='content',
            name='genres',
            field=models.ManyToManyField(related_name='contents', through='core.ContentGenre', to='core.genre'),
        ),
        migrations.AddField(
            model_name='content',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contentstatus'),
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, help_text='Pourcentage 0-100')),
                ('last_position', models.IntegerField(default=0, help_text='Position en secondes')),
                ('watched_duration', models.IntegerField(default=0, help_text='Durée regardée en secondes')),
                ('completed', models.BooleanField(default=False)),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.content')),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.episode')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='core.profile')),
            ],
            options={
                'db_table': 'watch_history',
                'indexes': [models.Index(fields=['profile', '-updated_at'], name='watch_histo_profile_ecd5c7_idx'), models.Index(fields=['content'], name='watch_histo_content_abdee8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ViewingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_watched', models.IntegerField(default=0, help_text='Durée en secondes')),
                ('was_completed', models.BooleanField(default=False)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('quality_played', models.CharField(blank=True, max_length=20)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.content')),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.episode')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_sessions', to='core.profile')),
            ],
            options={
                'db_table': 'viewing_sessions',
                'indexes': [models.Index(fields=['profile', '-start_time'], name='viewing_ses_profile_ab8fac_idx'), models.Index(fields=['content'], name='viewing_ses_content_c539c1_idx'), models.Index(fields=['session_id'], name='viewing_ses_session_8bd3ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrendingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('period', models.CharField(choices=[('day', 'Jour'), ('week', 'Semaine'), ('month', 'Mois')], max_length=20)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.content')),
            ],
            options={
                'db_table': 'trending_cache',
                'indexes': [models.Index(fields=['period', '-score'], name='trending_ca_period_ab6f16_idx')],
                'unique_together': {('content', 'period')},
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='subscriptio_user_id_8d58fd_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['expires_at'], name='subscriptio_expires_af5d7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('content', 'season_number')},
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['profile', '-score'], name='recommendat_profile_e4bc15_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('profile', 'content')},
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['content', '-rating'], name='ratings_content_8c98d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('profile', 'content')},
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='profiles_user_id_29277a_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['type'], name='profiles_type_id_f279f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['subscription'], name='payments_subscri_9bd444_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_status_d621e5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='notificatio_user_id_7336fd_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='notificatio_is_read_3f8c44_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_sent'], name='notificatio_is_sent_7b3d0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listitem',
            unique_together={('list', 'content')},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('profile', 'content')},
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('season', 'episode_number')},
        ),
        migrations.AddIndex(
            model_name='contentsimilarity',
            index=models.Index(fields=['-similarity_score'], name='content_sim_similar_9344ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentsimilarity',
            unique_together={('content_1', 'content_2')},
        ),
        migrations.AlterUniqueTogether(
            name='contentgenre',
            unique_together={('content', 'genre')},
        ),
        migrations.AlterUniqueTogether(
            name='contentemission',
            unique_together={('content', 'emission')},
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['type', 'status'], name='contents_type_8aa2fe_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['release_year'], name='contents_release_703c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['popularity_score'], name='contents_popular_e048a2_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['trending_score'], name='contents_trendin_09c770_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['title'], name='contents_title_c94f73_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='content_search_gin'),
        ),
    ]
