# Generated by Django 4.2.30 on 2026-08-12 19:25

import core.models.users
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_repair_admin_role_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminmfadevice",
            name="secret",
            field=models.CharField(
                default=core.models.users.generate_mfa_secret, max_length=64
            ),
        ),
        migrations.AddIndex(
            model_name="parentalpinresettoken",
            index=models.Index(fields=["token"], name="parental_pi_token_64441d_idx"),
        ),
        migrations.AddIndex(
            model_name="parentalpinresettoken",
            index=models.Index(
                fields=["profile", "expires_at"], name="parental_pi_profile_d1ed0e_idx"
            ),
        ),
    ]
