# Generated by Django 4.2.30 on 2026-09-01 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_subscriptionplanoffer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='ads_included_at_purchase',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='currency_at_purchase',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='subscription',
            name='download_enabled_at_purchase',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='duration_days_at_purchase',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='features_at_purchase',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='market_zone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_devices_at_purchase',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_profiles_at_purchase',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_quality_at_purchase',
            field=models.CharField(blank=True, choices=[('SD', 'SD'), ('HD', 'HD'), ('FULL_HD', 'Full HD'), ('4K', '4K')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price_at_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='regional_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='core.subscriptionplanoffer'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='tv_enabled_at_purchase',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
