# Generated by Django 4.2.30 on 2026-09-03 11:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_subscription_ads_included_at_purchase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAnalysisReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('passed', 'Passed'), ('review_required', 'Review required'), ('failed', 'Failed')], db_index=True, default='pending', max_length=30)),
                ('container', models.CharField(blank=True, max_length=50)),
                ('video_codec', models.CharField(blank=True, max_length=50)),
                ('audio_codec', models.CharField(blank=True, max_length=50)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('frame_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('video_bitrate', models.BigIntegerField(default=0)),
                ('audio_bitrate', models.BigIntegerField(default=0)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('audio_channels', models.PositiveSmallIntegerField(default=0)),
                ('sample_rate', models.PositiveIntegerField(default=0)),
                ('loudness_lufs', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('black_frame_count', models.PositiveIntegerField(default=0)),
                ('freeze_frame_count', models.PositiveIntegerField(default=0)),
                ('technical_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('moderation_scores', models.JSONField(blank=True, default=dict)),
                ('detected_events', models.JSONField(blank=True, default=list)),
                ('technical_metadata', models.JSONField(blank=True, default=dict)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('analysis_version', models.CharField(default='eke-qc-v1', max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_report', to='core.videoasset')),
            ],
            options={
                'db_table': 'media_analysis_reports',
                'indexes': [models.Index(fields=['status', 'created_at'], name='media_analy_status_60393b_idx')],
            },
        ),
    ]
