# Generated by Django 4.2.30 on 2026-09-03 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_mediaanalysisreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('registration_number', models.CharField(blank=True, help_text='Company/business registration number when applicable.', max_length=120)),
                ('tax_number', models.CharField(blank=True, max_length=120)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('representative_name', models.CharField(blank=True, max_length=255)),
                ('representative_role', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('onboarding', 'Onboarding'), ('contract_pending', 'Contract pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], db_index=True, default='onboarding', max_length=30)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producer_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'producer_accounts',
            },
        ),
        migrations.CreateModel(
            name='ProducerAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_version', models.CharField(max_length=50)),
                ('contract_title', models.CharField(max_length=255)),
                ('contract_hash', models.CharField(blank=True, help_text='SHA-256 hexadecimal hash of the exact contract document.', max_length=64)),
                ('contract_document_url', models.URLField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('superseded', 'Superseded'), ('terminated', 'Terminated')], db_index=True, default='pending', max_length=30)),
                ('signer_name', models.CharField(blank=True, max_length=255)),
                ('signer_role', models.CharField(blank=True, max_length=150)),
                ('signature_method', models.CharField(choices=[('clickwrap', 'Clickwrap'), ('external_esign', 'External electronic signature')], default='clickwrap', max_length=30)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('producer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='core.produceraccount')),
            ],
            options={
                'db_table': 'producer_agreements',
                'indexes': [models.Index(fields=['producer_account', 'status'], name='producer_agr_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='produceragreement',
            constraint=models.UniqueConstraint(fields=('producer_account', 'contract_version'), name='producer_agreement_version_unique'),
        ),
        migrations.AddIndex(
            model_name='produceraccount',
            index=models.Index(fields=['status', 'created_at'], name='producer_acc_status_idx'),
        ),
    ]
