# Generated by Django 4.2.30 on 2026-09-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_producer_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='produceraccount',
            name='legal_form',
            field=models.CharField(blank=True, help_text='Legal form of the producer, e.g. SAS, SARL, SA, LLC.', max_length=120),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='ekeflicks_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='ekeflicks_signer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='ekeflicks_signer_role',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='producer_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='producer_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='producer_country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='producer_legal_form',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='producer_legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='producer_registration_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='producer_representative_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='producer_representative_role',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='producer_tax_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='signed_document_hash',
            field=models.CharField(blank=True, help_text='SHA-256 of the final personalized signed PDF.', max_length=64),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='signed_document_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
