# Generated by Django 4.2.30 on 2026-09-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_produceraccount_legal_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produceragreement',
            name='presented_document_key',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='signed_document_key',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
