# Generated by Django 4.2.30 on 2026-09-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_produceragreement_presented_document_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='cast_team',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='content',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='content',
            name='director_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='content',
            name='director_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='content',
            name='language',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='content',
            name='producer_team',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='content',
            name='screenwriter_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='content',
            name='screenwriter_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
