# Generated by Django 4.2.30 on 2026-09-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_content_cast_team_content_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='backdrop_temp_path',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='content',
            name='director_image_temp_path',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='content',
            name='poster_temp_path',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='content',
            name='screenwriter_image_temp_path',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='content',
            name='trailer_temp_path',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
