# Generated by Django 4.2.30 on 2026-09-06 11:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_season_media_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSpecification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Cahier des charges technique EKEFLICKS', max_length=255)),
                ('version', models.CharField(max_length=50, unique=True)),
                ('introduction', models.TextField(blank=True)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'technical_specifications',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
