# Generated by Django 4.2.30 on 2026-09-06 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_technicalspecification'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='technical_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_contents', to='core.technicalspecification'),
        ),
        migrations.AddField(
            model_name='content',
            name='technical_specification_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
