# Generated by Django 4.2.30 on 2026-09-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_content_technical_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='audio_languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='content',
            name='subtitle_languages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
