# Generated by Django 4.2.30 on 2026-09-07 00:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_videoasset_delivery_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailerAnalysisReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('passed', 'Passed'), ('review_required', 'Review required'), ('failed', 'Failed')], db_index=True, default='pending', max_length=30)),
                ('source_path', models.CharField(blank=True, max_length=1000)),
                ('source_size_bytes', models.BigIntegerField(default=0)),
                ('container', models.CharField(blank=True, max_length=50)),
                ('video_codec', models.CharField(blank=True, max_length=50)),
                ('audio_codec', models.CharField(blank=True, max_length=50)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('frame_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('video_bitrate', models.BigIntegerField(default=0)),
                ('audio_bitrate', models.BigIntegerField(default=0)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('audio_channels', models.PositiveSmallIntegerField(default=0)),
                ('sample_rate', models.PositiveIntegerField(default=0)),
                ('technical_metadata', models.JSONField(blank=True, default=dict)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('analysis_version', models.CharField(default='eke-trailer-qc-v1', max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trailer_analysis_report', to='core.content')),
                ('season', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trailer_analysis_report', to='core.season')),
            ],
            options={
                'db_table': 'trailer_analysis_reports',
                'indexes': [models.Index(fields=['status', 'created_at'], name='trailer_ana_status_504c63_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='traileranalysisreport',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('content__isnull', False), ('season__isnull', True)), models.Q(('content__isnull', True), ('season__isnull', False)), _connector='OR'), name='trailer_analysis_exactly_one_target'),
        ),
    ]
