# Generated by Django 4.2.30 on 2026-09-09 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_traileranalysisreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.content')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.profile')),
            ],
            options={
                'db_table': 'likes',
                'indexes': [models.Index(fields=['content', '-created_at'], name='likes_content_998a45_idx'), models.Index(fields=['profile', '-created_at'], name='likes_profile_7625cb_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('profile', 'content'), name='unique_profile_content_like'),
        ),
    ]
