# Generated by Django 4.2.30 on 2026-09-11 17:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_like_like_unique_profile_content_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top10Snapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('window_start', models.DateTimeField(db_index=True)),
                ('window_end', models.DateTimeField(db_index=True)),
                ('scope', models.CharField(choices=[('global', 'Global')], db_index=True, default='global', max_length=32)),
                ('algorithm_version', models.CharField(default='d4_7d_v1', max_length=64)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'top10_snapshots',
                'ordering': ['-generated_at', '-id'],
                'indexes': [models.Index(fields=['scope', 'is_published', '-generated_at'], name='top10_snap_scope_pub_idx')],
            },
        ),
        migrations.CreateModel(
            name='Top10Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('qualified_views', models.PositiveBigIntegerField(default=0)),
                ('watch_seconds', models.PositiveBigIntegerField(default=0)),
                ('unique_viewers', models.PositiveBigIntegerField(default=0)),
                ('completed_views', models.PositiveBigIntegerField(default=0)),
                ('qualification_rate_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('previous_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('position_change', models.SmallIntegerField(blank=True, null=True)),
                ('movement', models.CharField(choices=[('new', 'New'), ('up', 'Up'), ('down', 'Down'), ('unchanged', 'Unchanged')], default='new', max_length=16)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='top10_entries', to='core.content')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.top10snapshot')),
            ],
            options={
                'db_table': 'top10_entries',
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['snapshot', 'position'], name='top10_entry_snap_pos_idx'), models.Index(fields=['content', '-snapshot'], name='top10_entry_content_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='top10entry',
            constraint=models.UniqueConstraint(fields=('snapshot', 'position'), name='uniq_top10_snapshot_position'),
        ),
        migrations.AddConstraint(
            model_name='top10entry',
            constraint=models.UniqueConstraint(fields=('snapshot', 'content'), name='uniq_top10_snapshot_content'),
        ),
        migrations.AddConstraint(
            model_name='top10entry',
            constraint=models.CheckConstraint(check=models.Q(('position__gte', 1), ('position__lte', 10)), name='top10_position_1_10'),
        ),
    ]
