# Generated by Django 4.2.30 on 2026-09-19 12:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_top10snapshot_top10entry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerContractVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('requires_reacceptance', models.BooleanField(default=True, help_text='Si active, cette version doit etre acceptee par les Producteurs meme si une ancienne version est signee.')),
                ('canonical_content', models.TextField(blank=True, help_text='Source contractuelle administrable de cette version. Une fois publiee, elle ne doit plus etre modifiee.')),
                ('content_sha256', models.CharField(blank=True, editable=False, help_text='SHA-256 du contenu contractuel canonique.', max_length=64)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'producer_contract_versions',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='producer_contract_pub_idx')],
            },
        ),
    ]
