# Generated by Django 4.2.30 on 2026-09-19 12:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_producercontractversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformLegalIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('legal_form', models.CharField(blank=True, max_length=100)),
                ('capital', models.CharField(blank=True, max_length=100)),
                ('registered_office', models.TextField()),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(default='France', max_length=120)),
                ('siret', models.CharField(blank=True, max_length=32)),
                ('rcs', models.CharField(blank=True, max_length=120)),
                ('vat_number', models.CharField(blank=True, max_length=64)),
                ('representative_name', models.CharField(blank=True, max_length=255)),
                ('representative_role', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('effective_from', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'platform_legal_identities',
                'ordering': ['-effective_from', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'effective_from'], name='platform_legal_active_idx')],
            },
        ),
    ]
