# Generated by Django 4.2.30 on 2026-09-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_platformlegalidentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='produceragreement',
            name='platform_capital',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='platform_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='platform_country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='platform_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='platform_legal_form',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='platform_legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='platform_postal_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='platform_rcs',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='platform_registered_office',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='platform_representative_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='platform_representative_role',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='platform_siret',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='platform_vat_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='produceragreement',
            name='platform_website',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
