import uuid

import django.db.models.deletion
from django.db import migrations, models


FAQ_ROWS = [
    # Producers: account and onboarding
    ('producer','Compte','Qui peut ouvrir un compte Producteur ?','Les producteurs indépendants, sociétés et studios peuvent s’inscrire s’ils disposent des droits nécessaires sur les œuvres proposées.','Who can create a producer account?','Independent producers, companies and studios may register if they hold the necessary rights to the works they submit.'),
    ('producer','Compte','Pourquoi dois-je vérifier mon adresse e-mail ?','La vérification sécurise le compte et permet de recevoir les étapes d’activation, les notifications et les confirmations liées à Finance.','Why must I verify my email address?','Email verification secures your account and enables activation steps, notifications and Finance confirmations.'),
    ('producer','Compte','Quelles informations professionnelles dois-je fournir ?','Renseignez les informations juridiques et de contact demandées dans Mon compte. Elles servent à identifier le producteur et à préparer le contrat.','What business information do I need to provide?','Complete the legal and contact information requested in My Account. It identifies the producer and is used to prepare the agreement.'),
    ('producer','Compte','Comment activer mon compte Producteur ?','Vérifiez votre adresse e-mail, complétez les informations professionnelles requises puis consultez et signez le contrat affiché dans votre espace.','How do I activate my producer account?','Verify your email, complete the required business information, then review and sign the agreement shown in your portal.'),
    ('producer','Compte','Puis-je modifier mes informations après l’inscription ?','Oui. Ouvrez Mon compte et choisissez Modifier mes informations. L’adresse e-mail ne se modifie pas dans le profil : envoyez une demande dédiée depuis Support.','Can I edit my information after registration?','Yes. Open My Account and choose Edit my information. Email cannot be changed from the profile; submit a dedicated request through Support.'),
    ('producer','Compte','Comment demander un changement d’adresse e-mail ?','Dans Support, choisissez Demande de changement d’e-mail, indiquez la nouvelle adresse et envoyez la demande. L’adresse actuelle reste inchangée pendant son traitement.','How do I request an email address change?','In Support, choose Email address change request, enter the new address and submit it. Your current address stays unchanged while the request is reviewed.'),
    ('producer','Compte','J’ai oublié mon mot de passe, que faire ?','Depuis la page de connexion, ouvrez Mot de passe oublié et suivez le lien reçu à l’adresse e-mail du compte.','What if I forgot my password?','On the login page, choose Forgot password and follow the link sent to the account email address.'),
    ('producer','Compte','Pourquoi mes pages restent-elles limitées après une nouvelle version du contrat ?','Une nouvelle version peut nécessiter une acceptation pour les actions contractuelles. Les producteurs dont le compte reste actif peuvent toujours consulter leurs propres données Analytics.','Why are some pages limited after a new agreement version?','A new version may require acceptance for contract-related actions. Producers whose account remains active can still view their own Analytics data.'),
    ('producer','Contrat','Où consulter et télécharger mon contrat ?','Ouvrez Mon contrat depuis votre espace. La version signée et son téléchargement sont disponibles lorsque le document a été archivé.','Where can I view and download my agreement?','Open My Agreement in your portal. The signed version and its download are available when the document has been archived.'),
    ('producer','Contrat','Pourquoi dois-je accepter une nouvelle version ?','EKEFLICKS peut publier une nouvelle version avec une date d’effet et une indication précisant si une nouvelle acceptation est nécessaire. Lisez le document affiché avant de signer.','Why do I need to accept a new version?','EKEFLICKS may publish a new version with an effective date and an indication of whether reacceptance is required. Review the displayed document before signing.'),
    ('producer','Dépôt','Quels types de contenus puis-je déposer ?','Votre espace de dépôt prend en charge les films et les séries avec saisons et épisodes. Les critères éditoriaux et les droits doivent être respectés.','What types of content can I submit?','The submission portal supports films and series with seasons and episodes. Editorial requirements and rights must be respected.'),
    ('producer','Dépôt','Puis-je enregistrer un brouillon avant de soumettre ?','Oui. Enregistrez votre dépôt comme brouillon, revenez le modifier puis soumettez-le lorsqu’il est complet.','Can I save a draft before submitting?','Yes. Save your submission as a draft, return to edit it, then submit it when it is complete.'),
    ('producer','Dépôt','Puis-je modifier un contenu déjà soumis ?','Un contenu en cours de validation ou déjà approuvé peut être verrouillé. Si une correction est demandée, utilisez le bouton de correction du contenu pour reprendre le dépôt.','Can I edit content that has already been submitted?','Content under review or already approved may be locked. If a correction is requested, use the content correction action to resume editing.'),
    ('producer','Dépôt','Comment déposer une série ?','Créez la série, puis ajoutez ses saisons et épisodes dans les rubriques prévues. Vérifiez chaque élément et enregistrez avant la soumission.','How do I submit a series?','Create the series, then add its seasons and episodes in the relevant sections. Review each item and save before submitting.'),
    ('producer','Dépôt','Puis-je importer des métadonnées depuis un fichier XML ?','Oui, si l’option Import XML est disponible dans le formulaire. Téléchargez d’abord le modèle correspondant au type de contenu, puis vérifiez l’aperçu avant de confirmer.','Can I import metadata from an XML file?','Yes, when XML Import is available in the form. Download the template for the selected content type, then review the preview before confirming.'),
    ('producer','Dépôt','Quelles images, vidéos et pièces sont obligatoires ?','Les exigences varient selon le contenu et peuvent évoluer. Consultez le cahier des charges technique depuis votre espace et les champs signalés comme obligatoires dans le formulaire.','Which images, videos and documents are required?','Requirements vary by content type and may change. Check the technical specification in your portal and the fields marked required in the form.'),
    ('producer','Dépôt','Pourquoi mon fichier est-il refusé ou en erreur ?','Vérifiez son format, sa taille, sa durée et les exigences indiquées dans le cahier des charges. Le rapport technique peut préciser la correction à effectuer.','Why was my file rejected or marked with an error?','Check its format, size, duration and the requirements in the technical specification. The technical report may identify the required correction.'),
    ('producer','Dépôt','À quoi sert le contrôle automatique des médias ?','Il vérifie des critères techniques et de qualité avant l’examen éditorial. Un résultat automatique ne remplace pas la décision finale de validation EKEFLICKS.','What is the automatic media check for?','It checks technical and quality criteria before editorial review. An automated result does not replace EKEFLICKS’ final approval decision.'),
    ('producer','Dépôt','Pourquoi mon contenu est-il encore en attente ?','Les dépôts passent par des contrôles techniques puis une validation EKEFLICKS. Consultez le statut et les éventuelles notifications dans Mes contenus.','Why is my content still pending?','Submissions go through technical checks and EKEFLICKS review. Check the status and notifications in My Content.'),
    ('producer','Dépôt','Comment corriger un contenu refusé ?','Ouvrez le contenu concerné, lisez le motif de correction, mettez à jour les champs ou fichiers demandés puis soumettez-le à nouveau.','How do I fix rejected content?','Open the content, review the correction reason, update the requested fields or files, then submit it again.'),
    ('producer','Dépôt','Puis-je supprimer un brouillon ?','Oui, depuis Mes films ou Mes séries. La suppression d’un brouillon est définitive; les règles de purge automatique éventuelles sont indiquées dans l’espace.','Can I delete a draft?','Yes, from My Films or My Series. Deleting a draft is permanent; any automatic cleanup rules are shown in the portal.'),
    ('producer','Métadonnées','Les titres et synopsis peuvent-ils être affichés en français et en anglais ?','Le portail conserve les métadonnées originales et peut générer une traduction de travail pour les champs pris en charge. Vérifiez les traductions avant leur publication.','Can titles and synopses appear in French and English?','The portal retains the original metadata and can generate a working translation for supported fields. Review translations before publication.'),
    ('producer','Métadonnées','Que se passe-t-il si je modifie un texte déjà traduit ?','Toute modification rend la traduction précédente obsolète. Une nouvelle traduction doit être générée et vérifiée avant sa publication.','What happens if I change text that was already translated?','Any edit makes the previous translation stale. A new translation must be generated and reviewed before publication.'),
    ('producer','Analytics','Pourquoi mes Analytics sont-ils vides ?','Les statistiques apparaissent lorsque des événements de visionnage sont collectés pour vos contenus. Vérifiez la période et le filtre sélectionnés; un contenu récent peut ne pas encore avoir de données.','Why is my Analytics page empty?','Statistics appear after viewing events are collected for your content. Check the selected period and filters; newly published content may not yet have data.'),
    ('producer','Analytics','Qui peut consulter mes statistiques ?','Les données Analytics producteurs sont limitées aux contenus associés à votre compte. Un identifiant de producteur fourni par le navigateur ne peut pas élargir cet accès.','Who can view my statistics?','Producer Analytics are restricted to content associated with your account. A producer identifier supplied by the browser cannot broaden access.'),
    ('producer','Finance','Comment sécuriser la page Finance ?','Lors du premier accès, créez un code Finance personnel à quatre chiffres puis confirmez-le avec le code reçu par e-mail. La vérification e-mail est demandée pour l’accès.','How do I secure the Finance page?','On first access, create a personal four-digit Finance PIN and confirm it using the code sent by email. Email verification is required for access.'),
    ('producer','Finance','J’ai oublié mon code Finance. Comment le réinitialiser ?','Sur l’écran de verrouillage Finance, choisissez Code oublié, confirmez le code reçu par e-mail puis définissez un nouveau code à quatre chiffres.','I forgot my Finance PIN. How do I reset it?','On the Finance lock screen, choose Forgot PIN, confirm the email code, then set a new four-digit PIN.'),
    ('producer','Finance','Quand une vue est-elle éligible à une rémunération ?','Une vue doit respecter le seuil de visionnage défini par le barème actif. Consultez Finance et votre contrat : le critère et les taux peuvent être administrés et mis à jour.','When does a view qualify for remuneration?','A view must meet the watch-time threshold in the active rules. Check Finance and your agreement; eligibility and rates are configurable and may change.'),
    ('producer','Finance','Comment les revenus publicitaires sont-ils partagés ?','La part producteur suit le pourcentage du barème actif et du contrat. Le tableau Finance détaille les montants attribués à chaque contenu.','How are advertising revenues shared?','The producer share follows the active rules and agreement. Finance shows amounts attributed to each content item.'),
    ('producer','Finance','Pourquoi les montants sont-ils affichés dans ma devise ?','Les montants affichés localement sont calculés à partir de l’équivalent EUR et du taux configuré pour le pays du compte. Le contrat conserve sa devise de référence et le paiement suit les règles applicables à la période.','Why are amounts shown in my currency?','Local amounts are calculated from the EUR equivalent and the configured rate for your account country. The agreement keeps its reference currency; payout follows the rules for the relevant period.'),
    ('producer','Finance','À partir de quel montant puis-je demander un paiement ?','Le seuil minimum apparaît dans Finance. Le montant disponible doit atteindre ce seuil et la rémunération du producteur doit être activée.','When can I request a payout?','The minimum threshold is shown in Finance. Your available balance must meet it and producer remuneration must be enabled.'),
    ('producer','Support','Comment contacter le support ?','Ouvrez Support, choisissez un sujet, décrivez votre demande et envoyez-la. Vous pourrez retrouver son statut et la réponse dans la même page.','How do I contact support?','Open Support, choose a subject, describe your request and submit it. You can track its status and reply on the same page.'),
    ('producer','Support','Comment signaler un problème de paiement ou de contenu ?','Créez une demande depuis Support en indiquant le contenu ou le paiement concerné et les éléments utiles. N’envoyez pas votre code Finance dans le message.','How do I report a payment or content issue?','Create a Support request and identify the content or payout involved, with relevant details. Never include your Finance PIN.'),
    ('producer','Eke et confidentialité','Comment activer ou retirer l’accès au micro, à la caméra ou à la géolocalisation ?','Dans Mon compte, cochez seulement les fonctions dont vous avez besoin. Le navigateur ou l’appareil peut demander son autorisation au moment d’utiliser la fonction. Vous pouvez décocher ces options dans Mon compte et retirer aussi la permission dans les réglages du navigateur ou de l’appareil.','How do I enable or withdraw microphone, camera or location access?','In My Account, check only the features you need. Your browser or device may ask for its permission when you use the feature. You can uncheck these options in My Account and also revoke the browser or device permission in its settings.'),
    ('producer','Eke et confidentialité','La géolocalisation me suit-elle en permanence ?','Non. La géolocalisation est facultative et aucune position n’est suivie en arrière-plan par le portail Producteur. La permission du navigateur ne suffit pas à autoriser un autre usage ou un partage de votre position.','Does geolocation track me continuously?','No. Geolocation is optional and the Producer portal does not track your location in the background. Browser permission alone does not authorize any other use or sharing of your location.'),
    ('producer','Eke et confidentialité','Eke peut-il analyser les données de tous les producteurs ?','Non. Eke Producteur consulte uniquement les statistiques de contenus appartenant au producteur connecté. Il peut aussi citer le Top 10 global lorsqu’un classement a été publié. Il ne consulte pas les statistiques internes complètes ni les données financières ou les contenus privés d’autres producteurs.','Can Eke analyze every producer’s data?','No. Eke Producer can only read analytics for content owned by the signed-in producer. It can also cite the published global Top 10. It cannot access full internal analytics, financial data or other producers’ private content.'),
    ('producer','Analytics','Pourquoi mon film est-il peu vu ?','Eke peut résumer les démarrages, vues qualifiées, spectateurs uniques et la complétion mesurés sur vos contenus. Ces indicateurs aident à repérer la portée ou la rétention, mais ne prouvent pas à eux seuls la cause. Eke précise la période utilisée.','Why does my film have few views?','Eke can summarize measured play starts, qualified views, unique viewers and completion for your content. These indicators help identify reach or retention patterns, but they do not prove a cause by themselves. Eke states the period used.'),
    ('producer','Analytics','Quel est le film en première position du Top 10 ?','Eke consulte le dernier instantané global Top 10 publié et indique la période couverte. Si aucun classement n’est publié ou accessible, il vous redirige vers Support au lieu d’inventer un résultat.','Which film is first in the Top 10?','Eke checks the latest published global Top 10 snapshot and gives its reporting period. If no ranking is published or available, it sends you to Support instead of inventing a result.'),
    ('producer','Eke','Comment choisir une voix masculine ou féminine pour Eke ?','Dans la page Eke, utilisez le sélecteur Voix et choisissez Homme ou Femme. Le choix dépend des voix installées dans votre navigateur ou appareil; si la voix choisie n’est pas disponible dans la langue sélectionnée, Eke vous l’indique.','How do I choose a male or female voice for Eke?','On the Eke page, use the Voice selector and choose Man or Woman. Availability depends on voices installed in your browser or device; Eke tells you if the selected voice is unavailable for the chosen language.'),
    # Clients
    ('client','Compte','Comment créer un compte client ?','Utilisez S’inscrire dans l’application ou sur le site EKEFLICKS, puis vérifiez l’adresse e-mail ou le numéro demandé.','How do I create a customer account?','Choose Sign up in the EKEFLICKS app or website, then verify the requested email address or phone number.'),
    ('client','Compte','J’ai oublié mon mot de passe.','Depuis la connexion, choisissez Mot de passe oublié et suivez le lien de réinitialisation reçu.','I forgot my password.','On the login screen, choose Forgot password and follow the password reset link you receive.'),
    ('client','Abonnement','Comment consulter les offres et leur prix ?','Les offres et prix applicables sont présentés dans la page Abonnements selon le pays et la devise pris en charge pour votre compte.','Where can I see plans and prices?','Available plans and prices are shown on the Subscriptions page for the country and currency supported by your account.'),
    ('client','Abonnement','Comment gérer ou annuler mon abonnement ?','Ouvrez votre compte puis la rubrique Abonnements pour consulter les options disponibles et le statut de renouvellement.','How do I manage or cancel my subscription?','Open your account and the Subscriptions section to review available options and renewal status.'),
    ('client','Lecture','Pourquoi je ne peux pas lire un programme ?','La disponibilité dépend de votre offre, du pays, des droits de diffusion et de la période de disponibilité. Consultez le message affiché dans la fiche du programme.','Why can’t I play a title?','Availability depends on your plan, country, distribution rights and availability dates. Check the message on the title page.'),
    ('client','Lecture','Comment reprendre une vidéo ?','Retrouvez le programme dans Continuer à regarder ou dans votre historique lorsque cette fonction est disponible sur votre appareil.','How can I resume a video?','Find the title in Continue Watching or your history when that feature is available on your device.'),
    ('client','Profils','Comment gérer les profils et le contrôle parental ?','Ouvrez les paramètres de profil pour gérer les profils disponibles et les options de contrôle parental associées à votre compte.','How do I manage profiles and parental controls?','Open profile settings to manage available profiles and the parental controls associated with your account.'),
    ('client','Support','Comment signaler un problème de lecture ou de facturation ?','Contactez le support depuis la rubrique Aide en indiquant votre appareil, le programme ou la transaction concernés et le message d’erreur.','How do I report a playback or billing issue?','Contact Support from Help and include your device, the title or transaction involved, and any error message.'),
    # Admins
    ('admin','Comptes','Comment modifier les réponses de la FAQ ?','Dans Django Admin, ouvrez Questions fréquentes. Modifiez les champs français et anglais, le public, la catégorie, l’ordre et l’état de publication.','How do I edit FAQ answers?','In Django Admin, open Frequently Asked Questions. Edit French and English fields, audience, category, order and publication status.'),
    ('admin','Comptes','Comment publier ou dépublier une réponse ?','Cochez ou décochez Publié. Les éléments non publiés ne sont pas fournis à l’API publique ni à l’assistant Eke.','How do I publish or unpublish an answer?','Toggle Published. Unpublished entries are not returned by the public API or Eke assistant.'),
    ('admin','Producteurs','Comment examiner une demande au support ?','Consultez Demandes support producteurs dans Django Admin, recherchez par e-mail ou sujet, puis consignez la réponse et mettez à jour le statut.','How do I review a producer support request?','Open Producer Support Requests in Django Admin, search by email or subject, record a reply and update the status.'),
    ('admin','Producteurs','Comment traiter une demande de changement d’e-mail ?','Examinez la demande dans Demandes de changement d’e-mail. Vérifiez l’identité du demandeur et l’unicité de la nouvelle adresse avant toute action; le statut seul ne modifie pas l’adresse du compte.','How do I process an email change request?','Review the request in Email Change Support Requests. Verify the requester and uniqueness of the new address before acting; changing request status alone does not update the account email.'),
    ('admin','Contrats','Comment publier une nouvelle version du contrat ?','Créez ou modifiez une version canonique, contrôlez son contenu et ses traductions, puis publiez-la avec la règle de réacceptation appropriée. Les accords signés restent des instantanés.','How do I publish a new agreement version?','Create or edit a canonical version, review its content and translations, then publish it with the appropriate reacceptance rule. Signed agreements remain snapshots.'),
    ('admin','Finance','Où modifier le barème producteur ?','Utilisez les réglages de rémunération producteurs. Vérifiez le montant par vue, le seuil de visionnage, la part publicitaire et le minimum de paiement avant publication.','Where can I change producer remuneration rules?','Use Producer Remuneration settings. Review the per-view rate, watch-time threshold, advertising share and payout minimum before applying changes.'),
    ('admin','Analytics','Pourquoi un producteur actif peut-il consulter Analytics sans nouvelle signature ?','La lecture Analytics vérifie le compte producteur actif et limite strictement les requêtes aux contenus dont il est propriétaire. L’acceptation d’une nouvelle version reste requise pour les actions contractuelles concernées.','Why can an active producer view Analytics without signing a new version?','Analytics checks the active producer account and strictly scopes queries to owned content. Reacceptance remains required for the affected contractual actions.'),
    ('admin','Sécurité','Comment vérifier que l’assistant Eke ne divulgue pas des données ?','Eke producteur répond depuis les FAQ publiées destinées aux producteurs. Il ne reçoit ni relevé financier ni données d’autres producteurs; les réponses inconnues renvoient vers Support.','How do I ensure Eke does not disclose private data?','Eke Producer answers from published producer FAQs. It receives no financial statements or other producers’ data; unknown questions are directed to Support.'),
]


def seed_faqs(apps, schema_editor):
    FAQ = apps.get_model('core', 'FrequentlyAskedQuestion')
    FAQ.objects.bulk_create([
        FAQ(
            id=uuid.uuid4(), audience=audience, category=category,
            question_fr=question_fr, answer_fr=answer_fr,
            question_en=question_en, answer_en=answer_en,
            sort_order=index * 10, is_published=True,
        )
        for index, (audience, category, question_fr, answer_fr, question_en, answer_en)
        in enumerate(FAQ_ROWS, 1)
    ])


class Migration(migrations.Migration):
    dependencies = [('core', '0051_producer_support_request')]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAskedQuestion',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, serialize=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audience', models.CharField(max_length=16, choices=[('producer', 'Producteurs'), ('client', 'Clients'), ('admin', 'Administration EKEFLICKS')], db_index=True)),
                ('category', models.CharField(max_length=48, db_index=True)),
                ('question_fr', models.CharField(max_length=240)),
                ('answer_fr', models.TextField()),
                ('question_en', models.CharField(max_length=240, blank=True)),
                ('answer_en', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True, db_index=True)),
            ],
            options={'db_table': 'frequently_asked_questions', 'ordering': ['audience', 'category', 'sort_order', 'id']},
        ),
        migrations.AddIndex(
            model_name='frequentlyaskedquestion',
            index=models.Index(fields=['audience', 'is_published', 'sort_order'], name='faq_aud_pub_sort_idx'),
        ),
        migrations.RunPython(seed_faqs, migrations.RunPython.noop),
    ]
