# Generated by Django 4.2.30 on 2026-09-12 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0042_top10snapshot_top10entry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], db_index=True, default='private', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=16)),
                ('capacity', models.PositiveSmallIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salons', to='core.content')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_salons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'salons',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SalonMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('host', 'Host'), ('member', 'Member')], default='member', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='salons.salon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'salon_members',
                'ordering': ('joined_at',),
                'indexes': [models.Index(fields=['salon', 'left_at'], name='salon_member_active_idx'), models.Index(fields=['user', 'left_at'], name='salon_user_active_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='salonmember',
            constraint=models.UniqueConstraint(condition=models.Q(('left_at__isnull', True)), fields=('salon', 'user'), name='salon_one_active_membership_per_user'),
        ),
        migrations.AddConstraint(
            model_name='salonmember',
            constraint=models.UniqueConstraint(condition=models.Q(('left_at__isnull', True), ('role', 'host')), fields=('salon',), name='salon_one_active_host'),
        ),
        migrations.AddIndex(
            model_name='salon',
            index=models.Index(fields=['status', 'visibility'], name='salon_status_visibility_idx'),
        ),
        migrations.AddIndex(
            model_name='salon',
            index=models.Index(fields=['host', 'status'], name='salon_host_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='salon',
            constraint=models.CheckConstraint(check=models.Q(('capacity__gte', 2), ('capacity__lte', 100)), name='salon_capacity_2_100'),
        ),
    ]
