# Generated by Django 4.2.30 on 2026-09-12 21:05

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonPlaybackState',
            fields=[
                ('salon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='playback_state', serialize=False, to='salons.salon')),
                ('position_ms', models.PositiveBigIntegerField(default=0)),
                ('is_playing', models.BooleanField(default=False)),
                ('playback_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('sequence', models.PositiveBigIntegerField(default=0)),
                ('last_event', models.CharField(choices=[('sync', 'Sync'), ('play', 'Play'), ('pause', 'Pause'), ('seek', 'Seek'), ('rate', 'Rate')], default='sync', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salon_playback_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'salon_playback_states',
            },
        ),
        migrations.AddConstraint(
            model_name='salonplaybackstate',
            constraint=models.CheckConstraint(check=models.Q(('playback_rate__gte', Decimal('0.50')), ('playback_rate__lte', Decimal('2.00'))), name='salon_playback_rate_050_200'),
        ),
    ]
