# Generated by Django 4.2.30 on 2026-09-13 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salons', '0002_salonplaybackstate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_invitations_received', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='salons.salon')),
            ],
            options={
                'db_table': 'salon_invitations',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['salon', 'status'], name='salon_invite_status_idx'), models.Index(fields=['invitee', 'status'], name='salon_invitee_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='saloninvitation',
            constraint=models.CheckConstraint(check=models.Q(('inviter', models.F('invitee')), _negated=True), name='salon_invitation_no_self'),
        ),
        migrations.AddConstraint(
            model_name='saloninvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('salon', 'invitee'), name='salon_one_pending_invitation_per_user'),
        ),
    ]
