# Generated by Django 4.2.30 on 2026-09-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0003_saloninvitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='mode',
            field=models.CharField(choices=[('social', 'Social'), ('friends', 'Friends'), ('mixed', 'Mixed'), ('thematic', 'Thematic')], db_index=True, default='social', max_length=16),
        ),
    ]
