# Generated by Django 4.2.30 on 2026-09-14 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salons', '0005_salonmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonSessionQuotaEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('consumed', 'Consumed'), ('released', 'Released')], db_index=True, default='reserved', max_length=16)),
                ('plan_slug', models.CharField(max_length=50)),
                ('first_guest_joined_at', models.DateTimeField(blank=True, null=True)),
                ('qualified_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_quota_entries', to=settings.AUTH_USER_MODEL)),
                ('salon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota_entry', to='salons.salon')),
            ],
            options={
                'db_table': 'salon_session_quota_entries',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['host', 'period_start', 'status'], name='salon_quota_period_idx')],
            },
        ),
    ]
