# Generated by Django 4.2.30 on 2026-09-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0006_salonsessionquotaentry'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salon',
            name='salon_capacity_2_100',
        ),
        migrations.AddField(
            model_name='salon',
            name='audio_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='video_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='salon',
            constraint=models.CheckConstraint(check=models.Q(('capacity__gte', 2), ('capacity__lte', 10)), name='salon_capacity_2_10'),
        ),
    ]
