class CountryOption {
  const CountryOption(this.code, this.name);

  final String code;
  final String name;

  String get label => '$name — $code';
}

const producerCountries = <CountryOption>[
  CountryOption('AF', 'Afghanistan'),
  CountryOption('ZA', 'Afrique du Sud'),
  CountryOption('AL', 'Albanie'),
  CountryOption('DZ', 'Algérie'),
  CountryOption('DE', 'Allemagne'),
  CountryOption('AD', 'Andorre'),
  CountryOption('AO', 'Angola'),
  CountryOption('SA', 'Arabie saoudite'),
  CountryOption('AR', 'Argentine'),
  CountryOption('AM', 'Arménie'),
  CountryOption('AU', 'Australie'),
  CountryOption('AT', 'Autriche'),
  CountryOption('AZ', 'Azerbaïdjan'),
  CountryOption('BS', 'Bahamas'),
  CountryOption('BH', 'Bahreïn'),
  CountryOption('BD', 'Bangladesh'),
  CountryOption('BB', 'Barbade'),
  CountryOption('BE', 'Belgique'),
  CountryOption('BZ', 'Belize'),
  CountryOption('BJ', 'Bénin'),
  CountryOption('BT', 'Bhoutan'),
  CountryOption('BY', 'Biélorussie'),
  CountryOption('BO', 'Bolivie'),
  CountryOption('BA', 'Bosnie-Herzégovine'),
  CountryOption('BW', 'Botswana'),
  CountryOption('BR', 'Brésil'),
  CountryOption('BN', 'Brunei'),
  CountryOption('BG', 'Bulgarie'),
  CountryOption('BF', 'Burkina Faso'),
  CountryOption('BI', 'Burundi'),
  CountryOption('KH', 'Cambodge'),
  CountryOption('CM', 'Cameroun'),
  CountryOption('CA', 'Canada'),
  CountryOption('CV', 'Cap-Vert'),
  CountryOption('CL', 'Chili'),
  CountryOption('CN', 'Chine'),
  CountryOption('CY', 'Chypre'),
  CountryOption('CO', 'Colombie'),
  CountryOption('KM', 'Comores'),
  CountryOption('CG', 'Congo'),
  CountryOption('CD', 'Congo (RDC)'),
  CountryOption('KR', 'Corée du Sud'),
  CountryOption('CR', 'Costa Rica'),
  CountryOption('CI', "Côte d'Ivoire"),
  CountryOption('HR', 'Croatie'),
  CountryOption('CU', 'Cuba'),
  CountryOption('DK', 'Danemark'),
  CountryOption('DJ', 'Djibouti'),
  CountryOption('DM', 'Dominique'),
  CountryOption('EG', 'Égypte'),
  CountryOption('AE', 'Émirats arabes unis'),
  CountryOption('EC', 'Équateur'),
  CountryOption('ER', 'Érythrée'),
  CountryOption('ES', 'Espagne'),
  CountryOption('EE', 'Estonie'),
  CountryOption('SZ', 'Eswatini'),
  CountryOption('US', 'États-Unis'),
  CountryOption('ET', 'Éthiopie'),
  CountryOption('FJ', 'Fidji'),
  CountryOption('FI', 'Finlande'),
  CountryOption('FR', 'France'),
  CountryOption('GA', 'Gabon'),
  CountryOption('GM', 'Gambie'),
  CountryOption('GE', 'Géorgie'),
  CountryOption('GH', 'Ghana'),
  CountryOption('GR', 'Grèce'),
  CountryOption('GD', 'Grenade'),
  CountryOption('GT', 'Guatemala'),
  CountryOption('GN', 'Guinée'),
  CountryOption('GW', 'Guinée-Bissau'),
  CountryOption('GQ', 'Guinée équatoriale'),
  CountryOption('GY', 'Guyana'),
  CountryOption('HT', 'Haïti'),
  CountryOption('HN', 'Honduras'),
  CountryOption('HU', 'Hongrie'),
  CountryOption('IN', 'Inde'),
  CountryOption('ID', 'Indonésie'),
  CountryOption('IQ', 'Irak'),
  CountryOption('IR', 'Iran'),
  CountryOption('IE', 'Irlande'),
  CountryOption('IS', 'Islande'),
  CountryOption('IL', 'Israël'),
  CountryOption('IT', 'Italie'),
  CountryOption('JM', 'Jamaïque'),
  CountryOption('JP', 'Japon'),
  CountryOption('JO', 'Jordanie'),
  CountryOption('KZ', 'Kazakhstan'),
  CountryOption('KE', 'Kenya'),
  CountryOption('KG', 'Kirghizistan'),
  CountryOption('KI', 'Kiribati'),
  CountryOption('KW', 'Koweït'),
  CountryOption('LA', 'Laos'),
  CountryOption('LS', 'Lesotho'),
  CountryOption('LV', 'Lettonie'),
  CountryOption('LB', 'Liban'),
  CountryOption('LR', 'Liberia'),
  CountryOption('LY', 'Libye'),
  CountryOption('LI', 'Liechtenstein'),
  CountryOption('LT', 'Lituanie'),
  CountryOption('LU', 'Luxembourg'),
  CountryOption('MK', 'Macédoine du Nord'),
  CountryOption('MG', 'Madagascar'),
  CountryOption('MY', 'Malaisie'),
  CountryOption('MW', 'Malawi'),
  CountryOption('MV', 'Maldives'),
  CountryOption('ML', 'Mali'),
  CountryOption('MT', 'Malte'),
  CountryOption('MA', 'Maroc'),
  CountryOption('MU', 'Maurice'),
  CountryOption('MR', 'Mauritanie'),
  CountryOption('MX', 'Mexique'),
  CountryOption('MD', 'Moldavie'),
  CountryOption('MC', 'Monaco'),
  CountryOption('MN', 'Mongolie'),
  CountryOption('ME', 'Monténégro'),
  CountryOption('MZ', 'Mozambique'),
  CountryOption('MM', 'Myanmar'),
  CountryOption('NA', 'Namibie'),
  CountryOption('NP', 'Népal'),
  CountryOption('NI', 'Nicaragua'),
  CountryOption('NE', 'Niger'),
  CountryOption('NG', 'Nigeria'),
  CountryOption('NO', 'Norvège'),
  CountryOption('NZ', 'Nouvelle-Zélande'),
  CountryOption('OM', 'Oman'),
  CountryOption('UG', 'Ouganda'),
  CountryOption('UZ', 'Ouzbékistan'),
  CountryOption('PK', 'Pakistan'),
  CountryOption('PA', 'Panama'),
  CountryOption('PY', 'Paraguay'),
  CountryOption('NL', 'Pays-Bas'),
  CountryOption('PE', 'Pérou'),
  CountryOption('PH', 'Philippines'),
  CountryOption('PL', 'Pologne'),
  CountryOption('PT', 'Portugal'),
  CountryOption('QA', 'Qatar'),
  CountryOption('CF', 'République centrafricaine'),
  CountryOption('DO', 'République dominicaine'),
  CountryOption('CZ', 'République tchèque'),
  CountryOption('RO', 'Roumanie'),
  CountryOption('GB', 'Royaume-Uni'),
  CountryOption('RU', 'Russie'),
  CountryOption('RW', 'Rwanda'),
  CountryOption('KN', 'Saint-Christophe-et-Niévès'),
  CountryOption('LC', 'Sainte-Lucie'),
  CountryOption('VC', 'Saint-Vincent-et-les-Grenadines'),
  CountryOption('SV', 'Salvador'),
  CountryOption('WS', 'Samoa'),
  CountryOption('ST', 'Sao Tomé-et-Principe'),
  CountryOption('SN', 'Sénégal'),
  CountryOption('RS', 'Serbie'),
  CountryOption('SC', 'Seychelles'),
  CountryOption('SL', 'Sierra Leone'),
  CountryOption('SG', 'Singapour'),
  CountryOption('SK', 'Slovaquie'),
  CountryOption('SI', 'Slovénie'),
  CountryOption('SO', 'Somalie'),
  CountryOption('SD', 'Soudan'),
  CountryOption('SS', 'Soudan du Sud'),
  CountryOption('LK', 'Sri Lanka'),
  CountryOption('SE', 'Suède'),
  CountryOption('CH', 'Suisse'),
  CountryOption('SR', 'Suriname'),
  CountryOption('SY', 'Syrie'),
  CountryOption('TJ', 'Tadjikistan'),
  CountryOption('TZ', 'Tanzanie'),
  CountryOption('TD', 'Tchad'),
  CountryOption('TH', 'Thaïlande'),
  CountryOption('TL', 'Timor oriental'),
  CountryOption('TG', 'Togo'),
  CountryOption('TO', 'Tonga'),
  CountryOption('TT', 'Trinité-et-Tobago'),
  CountryOption('TN', 'Tunisie'),
  CountryOption('TM', 'Turkménistan'),
  CountryOption('TR', 'Turquie'),
  CountryOption('TV', 'Tuvalu'),
  CountryOption('UA', 'Ukraine'),
  CountryOption('UY', 'Uruguay'),
  CountryOption('VU', 'Vanuatu'),
  CountryOption('VA', 'Vatican'),
  CountryOption('VE', 'Venezuela'),
  CountryOption('VN', 'Viêt Nam'),
  CountryOption('YE', 'Yémen'),
  CountryOption('ZM', 'Zambie'),
  CountryOption('ZW', 'Zimbabwe'),
];
