/// Returns the application route targeted by a password or parental-PIN link.
///
/// Reset links generated by the backend use query parameters at the root URL,
/// while older links use a dedicated path. Both formats remain supported.
String? deepLinkRoute(Uri uri) {
  final action = uri.queryParameters['action'];
  if (action == 'reset-password' || action == 'password-reset-confirm') {
    return '/reset-password';
  }
  if (action == 'reset-parental-pin') return '/reset-parental-pin';
  if (action == 'unsubscribe') return '/unsubscribe';

  if (uri.pathSegments.isEmpty) return null;
  switch (uri.pathSegments.first) {
    case 'reset-password':
    case 'password-reset-confirm':
      return '/reset-password';
    case 'reset-parental-pin':
      return '/reset-parental-pin';
    case 'unsubscribe':
      return '/unsubscribe';
    case 'payment':
      if (uri.pathSegments.length > 1 &&
          uri.pathSegments[1] == 'return') {
        return '/payment/return';
      }
      break;
  }
  return null;
}
